//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distribucion
    {
        public int Id_distribucion { get; set; }
        public int Id_plan { get; set; }
        public int Id_clavemateria { get; set; }
        public int Id_materia { get; set; }
        public int Id_grupo { get; set; }
        public int Id_hora { get; set; }
        public int Id_dia { get; set; }
        public int Id_salon { get; set; }
        public int Semestre { get; set; }
    
        public virtual ClaveMateria ClaveMateria { get; set; }
        public virtual Dia Dia { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual Hora Hora { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual PlanEstudios PlanEstudios { get; set; }
        public virtual Salon Salon { get; set; }
        public virtual Semestre Semestre1 { get; set; }
    }
}
